-- MySQL Script generated by MySQL Workbench
-- Sun Mar 13 07:33:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema toquedivino
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema toquedivino
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toquedivino` DEFAULT CHARACTER SET utf8 ;
USE `toquedivino` ;

-- -----------------------------------------------------
-- Table `toquedivino`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` BINARY(16) NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 0 COMMENT '0 = disable\n1 = enable',
  `phone` VARCHAR(45) NULL,
  `photo` VARCHAR(100) NULL,
  `pin` INT NULL,
  `access` INT NULL DEFAULT 0 COMMENT '0 = adm\n1 = user\n2 = client\n3 = musician\n4 = signature',
  PRIMARY KEY (`idaccount`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`inscribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`inscribe` (
  `idinscribe` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `accountable` VARCHAR(100) NOT NULL,
  `bithdate` DATE NULL,
  `phone` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `address` MEDIUMTEXT NULL COMMENT 'logradouro, número, complemento, bairro, cidade, estado, país',
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `account_idaccount` INT NOT NULL,
  `status` INT NULL COMMENT '0 = cadastro\n1 = contrato não validado\n2 = contrtato validado\n3 = cancelado',
  PRIMARY KEY (`idinscribe`),
  INDEX `fk_inscribe_account1_idx` (`account_idaccount` ASC) VISIBLE)
ENGINE = FEDERATED;


-- -----------------------------------------------------
-- Table `toquedivino`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`service` (
  `idservice` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `status` INT NULL DEFAULT 1 COMMENT '0 = disable\n1 = enable',
  PRIMARY KEY (`idservice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`engaged`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`engaged` (
  `idengaged` INT NOT NULL AUTO_INCREMENT,
  `groom_name` VARCHAR(100) NOT NULL,
  `groom_address` MEDIUMTEXT NOT NULL COMMENT 'logradouro, número, complemento, bairro, cidade, estado, país',
  `groom_phone` VARCHAR(45) NULL,
  `groom_mobile` VARCHAR(45) NOT NULL,
  `groom_photo` VARCHAR(200) NULL,
  `groom_cpf` VARCHAR(45) NULL,
  `groom_rg` VARCHAR(45) NULL,
  `groom_birthdate` DATE NULL,
  `groom_email` VARCHAR(100) NULL,
  `groom_responsible_for` INT NULL DEFAULT 0,
  `bride_name` VARCHAR(100) NOT NULL,
  `bride_address` MEDIUMTEXT NOT NULL,
  `bride_phone` VARCHAR(45) NULL,
  `bride_mobile` VARCHAR(45) NOT NULL,
  `bride_photo` VARCHAR(200) NULL,
  `bride_cpf` VARCHAR(45) NULL,
  `bride_rg` VARCHAR(45) NULL,
  `bride_birthdate` DATE NULL,
  `bride_email` VARCHAR(45) NULL,
  `bride_responsible_for` INT NULL DEFAULT 0,
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`idengaged`, `inscribe_idinscribe`),
  INDEX `fk_engaged_inscribe1_idx` USING BTREE (`inscribe_idinscribe`) INVISIBLE,
  CONSTRAINT `fk_engaged_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`event` (
  `idevent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  `address` MEDIUMTEXT NULL COMMENT 'logradouro, número, complemento, bairro, cidade, estado, país',
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`idevent`, `inscribe_idinscribe`),
  INDEX `fk_event_inscribe1_idx` (`inscribe_idinscribe` ASC) VISIBLE,
  CONSTRAINT `fk_event_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`graduation_committe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`graduation_committe` (
  `idgraduation_committe` INT NOT NULL AUTO_INCREMENT,
  `committe_name` MEDIUMTEXT NOT NULL COMMENT 'nome, função',
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`idgraduation_committe`, `inscribe_idinscribe`),
  INDEX `fk_graduation_committe_inscribe1_idx` (`inscribe_idinscribe` ASC) VISIBLE,
  CONSTRAINT `fk_graduation_committe_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`instrument` (
  `idinstrument` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sound` VARCHAR(100) NULL,
  `image` VARCHAR(100) NULL,
  PRIMARY KEY (`idinstrument`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`formation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`formation` (
  `idformation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `price` FLOAT NOT NULL,
  `video` VARCHAR(200) NULL,
  PRIMARY KEY (`idformation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`formation_has_instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`formation_has_instrument` (
  `formation_idformation` INT NOT NULL,
  `instrument_idinstrument` INT NOT NULL,
  PRIMARY KEY (`formation_idformation`, `instrument_idinstrument`),
  INDEX `fk_formation_has_instrument_instrument1_idx` (`instrument_idinstrument` ASC) INVISIBLE,
  INDEX `fk_formation_has_instrument_formation1_idx` (`formation_idformation` ASC) INVISIBLE,
  CONSTRAINT `fk_formation_has_instrument_formation1`
    FOREIGN KEY (`formation_idformation`)
    REFERENCES `toquedivino`.`formation` (`idformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formation_has_instrument_instrument1`
    FOREIGN KEY (`instrument_idinstrument`)
    REFERENCES `toquedivino`.`instrument` (`idinstrument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`tax` (
  `idtax` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `value` FLOAT NOT NULL,
  `type` INT NOT NULL COMMENT '1 = fixa\n2 = multiplicada\n\nquando a taxa for do tipo 2 (multiplicada) precisa ter variante, valor que  pondera com o valor da taxa',
  `multiplied` VARCHAR(45) NULL,
  PRIMARY KEY (`idtax`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`service_has_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`service_has_tax` (
  `service_idservice` INT NOT NULL,
  `tax_idtax` INT NOT NULL,
  PRIMARY KEY (`service_idservice`, `tax_idtax`),
  INDEX `fk_service_has_tax_tax1_idx` (`tax_idtax` ASC) INVISIBLE,
  INDEX `fk_service_has_tax_service1_idx` (`service_idservice` ASC) INVISIBLE,
  CONSTRAINT `fk_service_has_tax_service1`
    FOREIGN KEY (`service_idservice`)
    REFERENCES `toquedivino`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_has_tax_tax1`
    FOREIGN KEY (`tax_idtax`)
    REFERENCES `toquedivino`.`tax` (`idtax`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`agreement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`agreement` (
  `idagreement` INT NOT NULL AUTO_INCREMENT,
  `code` BIGINT(20) NOT NULL,
  `date` DATETIME NULL,
  `value` FLOAT NULL,
  `discount` FLOAT NULL,
  `addition` FLOAT NULL,
  `down_payment` FLOAT NULL,
  `down_payment_date` DATE NULL,
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`idagreement`),
  INDEX `fk_agreement_inscribe1_idx` (`inscribe_idinscribe` ASC) VISIBLE,
  CONSTRAINT `fk_agreement_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`composition` (
  `idcomposition` INT NOT NULL AUTO_INCREMENT,
  `service_idservice` INT NOT NULL,
  `formation_idformation` INT NOT NULL,
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`idcomposition`),
  INDEX `fk_composition_service1_idx` (`service_idservice` ASC) INVISIBLE,
  INDEX `fk_composition_formation1_idx` (`formation_idformation` ASC) INVISIBLE,
  INDEX `fk_composition_inscribe1_idx` (`inscribe_idinscribe` ASC) INVISIBLE,
  CONSTRAINT `fk_composition_service1`
    FOREIGN KEY (`service_idservice`)
    REFERENCES `toquedivino`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_formation1`
    FOREIGN KEY (`formation_idformation`)
    REFERENCES `toquedivino`.`formation` (`idformation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`composition_has_instrument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`composition_has_instrument` (
  `composition_idcomposition` INT NOT NULL,
  `instrument_idinstrument` INT NOT NULL,
  PRIMARY KEY (`composition_idcomposition`, `instrument_idinstrument`),
  INDEX `fk_composition_has_instrument_instrument1_idx` (`instrument_idinstrument` ASC) INVISIBLE,
  INDEX `fk_composition_has_instrument_composition1_idx` (`composition_idcomposition` ASC) INVISIBLE,
  CONSTRAINT `fk_composition_has_instrument_composition1`
    FOREIGN KEY (`composition_idcomposition`)
    REFERENCES `toquedivino`.`composition` (`idcomposition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_has_instrument_instrument1`
    FOREIGN KEY (`instrument_idinstrument`)
    REFERENCES `toquedivino`.`instrument` (`idinstrument`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`log_logon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`log_logon` (
  `idlog_logon` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  `account_idaccount` INT NOT NULL,
  PRIMARY KEY (`idlog_logon`),
  INDEX `fk_log_logon_account1_idx` (`account_idaccount` ASC) VISIBLE,
  CONSTRAINT `fk_log_logon_account1`
    FOREIGN KEY (`account_idaccount`)
    REFERENCES `toquedivino`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`log_visitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`log_visitor` (
  `idlog_visitor` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  `page` VARCHAR(45) NULL,
  PRIMARY KEY (`idlog_visitor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`log_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`log_event` (
  `idlog_event` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  `event` VARCHAR(45) NULL,
  `log_visitor_idlog_visitor` INT NOT NULL,
  PRIMARY KEY (`idlog_event`),
  INDEX `fk_log_event_log_visitor1_idx` (`log_visitor_idlog_visitor` ASC) VISIBLE,
  CONSTRAINT `fk_log_event_log_visitor1`
    FOREIGN KEY (`log_visitor_idlog_visitor`)
    REFERENCES `toquedivino`.`log_visitor` (`idlog_visitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`pre_inscribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`pre_inscribe` (
  `idpre_inscribe` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  `origin` VARCHAR(200) NULL,
  `accountable` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `mobile` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `flag` INT NULL DEFAULT 0,
  PRIMARY KEY (`idpre_inscribe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`variant_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`variant_tax` (
  `value` VARCHAR(45) NULL,
  `tax_idtax` INT NOT NULL,
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`tax_idtax`, `inscribe_idinscribe`),
  INDEX `fk_variant_tax_inscribe1_idx` (`inscribe_idinscribe` ASC) INVISIBLE,
  CONSTRAINT `fk_variant_tax_tax1`
    FOREIGN KEY (`tax_idtax`)
    REFERENCES `toquedivino`.`tax` (`idtax`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_variant_tax_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`pre_inscribe_has_inscribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`pre_inscribe_has_inscribe` (
  `pre_inscribe_idpre_inscribe` INT NOT NULL,
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`pre_inscribe_idpre_inscribe`, `inscribe_idinscribe`),
  INDEX `fk_pre_inscribe_has_inscribe_inscribe1_idx` (`inscribe_idinscribe` ASC) VISIBLE,
  INDEX `fk_pre_inscribe_has_inscribe_pre_inscribe1_idx` (`pre_inscribe_idpre_inscribe` ASC) VISIBLE,
  CONSTRAINT `fk_pre_inscribe_has_inscribe_pre_inscribe1`
    FOREIGN KEY (`pre_inscribe_idpre_inscribe`)
    REFERENCES `toquedivino`.`pre_inscribe` (`idpre_inscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pre_inscribe_has_inscribe_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`music` (
  `idmusic` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `status` INT NULL DEFAULT 1 COMMENT '0 = disable\n1 = enable',
  PRIMARY KEY (`idmusic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`repertory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`repertory` (
  `idrepertory` INT NOT NULL AUTO_INCREMENT,
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`idrepertory`),
  INDEX `fk_repertory_inscribe1_idx` (`inscribe_idinscribe` ASC) VISIBLE,
  CONSTRAINT `fk_repertory_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`moments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`moments` (
  `idmoments` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL DEFAULT 1 COMMENT '0 = disable\n1 = enable',
  PRIMARY KEY (`idmoments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`moments_has_repertory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`moments_has_repertory` (
  `moments_idmoments` INT NOT NULL,
  `repertory_idrepertory` INT NOT NULL,
  `music_idmusic` INT NOT NULL,
  `sequence` INT NULL,
  PRIMARY KEY (`moments_idmoments`, `repertory_idrepertory`, `music_idmusic`),
  INDEX `fk_moments_has_repertory_repertory1_idx` (`repertory_idrepertory` ASC) VISIBLE,
  INDEX `fk_moments_has_repertory_moments1_idx` (`moments_idmoments` ASC) VISIBLE,
  INDEX `fk_moments_has_repertory_music1_idx` (`music_idmusic` ASC) VISIBLE,
  CONSTRAINT `fk_moments_has_repertory_moments1`
    FOREIGN KEY (`moments_idmoments`)
    REFERENCES `toquedivino`.`moments` (`idmoments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moments_has_repertory_repertory1`
    FOREIGN KEY (`repertory_idrepertory`)
    REFERENCES `toquedivino`.`repertory` (`idrepertory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moments_has_repertory_music1`
    FOREIGN KEY (`music_idmusic`)
    REFERENCES `toquedivino`.`music` (`idmusic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`moments_has_music`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`moments_has_music` (
  `moments_idmoments` INT NOT NULL,
  `music_idmusic` INT NOT NULL,
  PRIMARY KEY (`moments_idmoments`, `music_idmusic`),
  INDEX `fk_moments_has_music_music1_idx` (`music_idmusic` ASC) VISIBLE,
  INDEX `fk_moments_has_music_moments1_idx` (`moments_idmoments` ASC) VISIBLE,
  CONSTRAINT `fk_moments_has_music_moments1`
    FOREIGN KEY (`moments_idmoments`)
    REFERENCES `toquedivino`.`moments` (`idmoments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moments_has_music_music1`
    FOREIGN KEY (`music_idmusic`)
    REFERENCES `toquedivino`.`music` (`idmusic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`log_marketing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`log_marketing` (
  `idlog_marketing` INT NOT NULL AUTO_INCREMENT,
  `action` INT NOT NULL COMMENT '1 = Email\n2 = WhatsApp',
  `datetime` DATETIME NOT NULL,
  `pre_inscribe_idpre_inscribe` INT NOT NULL,
  PRIMARY KEY (`idlog_marketing`),
  CONSTRAINT `fk_log_marketing_pre_inscribe1`
    FOREIGN KEY (`pre_inscribe_idpre_inscribe`)
    REFERENCES `toquedivino`.`pre_inscribe` (`idpre_inscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`signature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`signature` (
  `idsignature` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `type` INT NULL COMMENT '1 = contratante\n2 = contratado\n3 = testemunha\n',
  `font` VARCHAR(45) NULL,
  `status` INT NULL,
  `inuse` INT NULL,
  `account_idaccount` INT NOT NULL,
  PRIMARY KEY (`idsignature`),
  INDEX `fk_signature_account1_idx` (`account_idaccount` ASC) INVISIBLE,
  CONSTRAINT `fk_signature_account1`
    FOREIGN KEY (`account_idaccount`)
    REFERENCES `toquedivino`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`agreement_has_signature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`agreement_has_signature` (
  `agreement_idagreement` INT NOT NULL,
  `signature_idsignature` INT NOT NULL,
  `inscribe_idinscribe` INT NOT NULL,
  `sign` INT NULL COMMENT '0 = no',
  `date` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  `geolocation` VARCHAR(200) NULL,
  `hash` MEDIUMTEXT NULL,
  PRIMARY KEY (`agreement_idagreement`, `signature_idsignature`, `inscribe_idinscribe`),
  INDEX `fk_agreement_has_signature_signature1_idx` (`signature_idsignature` ASC) VISIBLE,
  INDEX `fk_agreement_has_signature_inscribe1_idx` (`inscribe_idinscribe` ASC) VISIBLE,
  CONSTRAINT `fk_agreement_has_signature_agreement1`
    FOREIGN KEY (`agreement_idagreement`)
    REFERENCES `toquedivino`.`agreement` (`idagreement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agreement_has_signature_signature1`
    FOREIGN KEY (`signature_idsignature`)
    REFERENCES `toquedivino`.`signature` (`idsignature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agreement_has_signature_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`wedding_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`wedding_services` (
  `idwedding_services` INT NOT NULL AUTO_INCREMENT,
  `companyname` VARCHAR(200) NULL,
  `address` MEDIUMTEXT NULL COMMENT 'object { street, number, complement, zipcode, disctirct, city, country }',
  `phone` VARCHAR(45) NULL,
  `contactname` VARCHAR(200) NULL,
  `engaged_idengaged` INT NOT NULL,
  PRIMARY KEY (`idwedding_services`),
  INDEX `fk_weddinig_services_engaged1_idx` (`engaged_idengaged` ASC) VISIBLE,
  CONSTRAINT `fk_weddinig_services_engaged1`
    FOREIGN KEY (`engaged_idengaged`)
    REFERENCES `toquedivino`.`engaged` (`idengaged`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toquedivino`.`budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toquedivino`.`budget` (
  `idbudget` INT NOT NULL AUTO_INCREMENT,
  `code` BIGINT(20) NULL,
  `date` DATETIME NOT NULL,
  `value` FLOAT NOT NULL,
  `discount` FLOAT NULL,
  `addition` FLOAT NULL,
  `expires_in` DATETIME NOT NULL,
  `inscribe_idinscribe` INT NOT NULL,
  PRIMARY KEY (`idbudget`),
  INDEX `fk_budget_inscribe1_idx` (`inscribe_idinscribe` ASC) VISIBLE,
  CONSTRAINT `fk_budget_inscribe1`
    FOREIGN KEY (`inscribe_idinscribe`)
    REFERENCES `toquedivino`.`inscribe` (`idinscribe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
